#! /usr/bin/env python
import socket#, _mypath
from wsgiref.simple_server import make_server
from app import MyApp
import random

if __name__ == '__main__':
    #port = 8080
    port = random.randrange(8081, 9099) 

    app = MyApp()

    httpd = make_server('',port,app)
    print "Serving on port %d....." % port
    print "Try using a Web browser to go to http://%s:%d/" % \
            (socket.getfqdn(), port)
    httpd.serve_forever()
